"""empty message

Revision ID: f8d758d72ff0
Revises: 7d811d7c604e
Create Date: 2022-06-16 22:21:38.059023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d758d72ff0'
down_revision = '7d811d7c604e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'upcoming')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('upcoming', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
